[broken.packages]
name = [
    "Arduino",
    "ChainRecursive",
    "Chunks",
    "CombinatorialBandits",
    "ControlCore",
    "DotOverloading",
    "DriftDiffusion",
    "DynamicalBilliardsPlotting",
    "Expect",
    "GLUT",
    "GetC",
    "HTSLIB",
    "KeyedTables",
    "Keys",
    "LazyCall",
    "LazyContext",
    "LazyQuery",
    "MichiganAutonomousVehicles",
    "NumberedLines",
    "OnlineMoments",
    "OnlinePackage",
    "OpenGL",
    "OrthogonalPolynomials",
    "Parts",
    "PhasedArrayTracking",
    "Polyglot",
    "React",
    "RecurUnroll",
    "RequirementVersions",
    "SDL",
    "SessionHacker",
    "SimilarReferences",
    "Sparrow",
    "StringArrays",
    "TypedBools",
    "ZippedArrays",
]
